pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/BSSE23081/devsolutions-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devsolutions-backend:latest ./backend'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh '''
                        echo "$PASS" | docker login -u "$USER" --password-stdin
                        docker tag devsolutions-backend:latest $USER/devsolutions-backend:latest
                        docker push $USER/devsolutions-backend:latest
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                    kubectl apply -f k8s/backend.yaml
                '''
            }
        }
    }
}
